env:
  - STRATEGY_UNDER_TEST=b

# decrypt .env file...
before_install: openssl aes-256-cbc -K $encrypted_0cf3493bd01c_key -iv $encrypted_0cf3493bd01c_iv -in b/.env.enc -out b/.env -d

script: cd $STRATEGY_UNDER_TEST; exec test/harness

