#!/bin/bash

set -eux
set -o pipefail

# Travis CI provisioning..
if [ -n "${CI:-}" ]; then
  openssl aes-256-cbc -K $encrypted_0cf3493bd01c_key -iv $encrypted_0cf3493bd01c_iv -in .env.enc -out .env -d
  go get github.com/tools/godep
  sudo apt-get install jq zbackup
fi

# build & install the thing
make
sudo make install

# load env variables if present
if [ -e .env ]; then
  source .env
  export $(cut -d= -f1 .env)
fi

test/t-dataroundtrip.sh

echo "all tests passed!"
