#!/bin/bash

set -eux
set -o pipefail

# Travis CI provisioning..
if [ -n "${CI:-}" ]; then
  openssl aes-256-cbc -K $encrypted_ad436cd0a302_key -iv $encrypted_ad436cd0a302_iv -in .creds.enc -out ~/.haven-b-gdrivecreds -d
  export GOPATH="$HOME/go"
  export PATH="$PATH:$GOPATH/bin"

  go get github.com/tools/godep

  sudo apt-get update
  sudo apt-get install buffer gnupg-agent golang zfs-fuse

  # ehehehe
  sudo rm /dev/random
  sudo ln -s /dev/urandom /dev/random
fi

# generate a gpg key
export GNUPGHOME=$(mktemp -d /tmp/gpgXXXXXX)
echo "Key-Type: RSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: Joe Tester
Name-Email: joe@foo.bar
Expire-Date: 0
%commit" | gpg --gen-key --batch
echo hai | gpg -es -r joe@foo.bar | gpg -d > /dev/null # make sure it works

# build & install the thing
make
sudo make install

vdev=$(mktemp /tmp/testpoolvdevXXXXXX)
dd if=/dev/zero of=$vdev bs=512 count=800000
pool=$(basename $vdev)
sudo zpool create $pool $vdev
# schedule unlink
rm $vdev

. test/t-dataroundtrip.sh $pool

sudo zpool destroy $pool
echo "all tests passed!"
