#!/bin/bash

set -eux

backup=$1
bundles="$(dirname $backup)/../bundles"

# simulate moving away all the bundles (i.e. archiving to S3)
archive="$bundles/../archived_bundles"
mkdir -p $archive
pushd $bundles
ls | xargs -I {} mkdir -p $archive/{}
find . -type f | xargs -n 1 -I {} mv {} $archive/{}
popd
rmdir $bundles/* || true
